# Generated by Django 3.0.3 on 2020-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='moodleID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
